# Generated by Django 5.0.1 on 2024-03-08 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
