# Generated by Django 5.0.1 on 2024-01-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innercargo',
            options={'verbose_name': 'اعلام بار داخلی', 'verbose_name_plural': 'اعلام بار های  داخلی'},
        ),
        migrations.AlterModelOptions(
            name='internationalcargo',
            options={'verbose_name': 'اعلام بار خارجی', 'verbose_name_plural': 'اعلام بار های خارجی'},
        ),
    ]
