# Generated by Django 5.0.1 on 2024-01-27 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carrier_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwReqDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_type', models.CharField(choices=[('permanent', 'همکاری دائم (تمام وقت)'), ('temporary', 'همکاری موقت (پاره وقت)')], max_length=40, verbose_name='نوع همکاری')),
                ('origin', models.CharField(max_length=255, verbose_name='مبدا')),
                ('destination', models.CharField(max_length=255, verbose_name='مقصد')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت پیشنهادی')),
                ('carrier_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.carrierowner', verbose_name='حمل کننده')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver', verbose_name='راننده')),
                ('goods_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='صاحب حمل کننده')),
            ],
            options={
                'verbose_name': 'درخواست همکاری صاحب حمل کننده از راننده',
                'verbose_name_plural': 'درخواست\u200cهای همکاری صاحب حمل کننده از راننده',
            },
        ),
    ]
