# Generated by Django 5.0.1 on 2024-01-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadfleet',
            name='carrier_in',
        ),
        migrations.RemoveField(
            model_name='roadfleet',
            name='carrier_out',
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='carrier_type',
            field=models.CharField(choices=[('حمل و نقل داخلی', 'حمل و نقل داخلی'), ('حمل و نقل بین المللی', 'حمل و نقل بین المللی')], default='حمل و نقل بین المللی', max_length=30, verbose_name='نوع حمل و نقل'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='semiHeavyVehichle',
            field=models.CharField(choices=[('کامیون', 'کامیون'), ('خاور', 'خاور'), ('هیوندا', 'هیوندا'), ('ماشین باربری ایسوزو', 'ماشین باربری ایسوزو'), ('کامیونت', 'کامیونت')], default='', max_length=20, verbose_name='ماشین باربری نیمه سنگین'),
        ),
    ]
