# Generated by Django 5.0.1 on 2024-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadfleet',
            name='HeavyVehichle',
        ),
        migrations.RemoveField(
            model_name='roadfleet',
            name='heavy_vehicle_others',
        ),
        migrations.RemoveField(
            model_name='roadfleet',
            name='semiHeavyVehichle',
        ),
        migrations.RemoveField(
            model_name='roadfleet',
            name='semiHeavyVehichleOthers',
        ),
        migrations.RemoveField(
            model_name='roadfleet',
            name='vehichleTypeOthers',
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='roomType',
            field=models.CharField(choices=[('چادری', 'چادری'), ('روباز', 'روباز'), ('یخچالی', 'یخچالی'), ('کمپرسی', 'کمپرسی'), ('مسقف', 'مسقف'), ('کفی', 'کفی'), ('بفل دار', 'بقل دار')], default='', max_length=100, verbose_name='نوع اتاق'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='vehichleType',
            field=models.CharField(choices=[('تریلی', 'تریلی'), ('جفت', 'جفت'), ('تک', 'تک'), ('خاور', 'خاور'), ('وانت و نیسان', 'وانت ونیسان'), ('خاور', 'خاور')], default='', max_length=100, verbose_name='نوع وسیله حمل کننده'),
        ),
    ]
