# Generated by Django 5.0.1 on 2024-02-20 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('carrier_owner', '0001_initial'),
        ('goods_owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carowreqgoodsowner',
            name='required_carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredcarrier', verbose_name='درخواست صاحب بار'),
        ),
        migrations.AddField(
            model_name='carowreqgoodsowner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='carrier_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carrierowner', verbose_name='صاحب حمل کننده'),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط '),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='required_carriers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='carowreqgoodsowner',
            name='road_fleet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_owners', to='carrier_owner.roadfleet', verbose_name='حمل کننده'),
        ),
        migrations.AddField(
            model_name='carowreqdriver',
            name='carrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier_owner.roadfleet', verbose_name='حمل کننده'),
        ),
    ]
