# Generated by Django 5.0.1 on 2024-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadfleet',
            name='carrier_type',
            field=models.CharField(choices=[('حمل و نقل داخلی', 'حمل و نقل داخلی'), ('حمل و نقل بین المللی', 'حمل و نقل بین المللی'), ('داخلی و بین المللی', 'داخلی و بین المللی')], default='حمل و نقل بین المللی', max_length=40, verbose_name='نوع حمل و نقل'),
        ),
    ]
