# Generated by Django 5.0.1 on 2024-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0003_alter_carowreqdriver_request_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowreqdriver',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='carowreqdriver',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است؟'),
        ),
        migrations.AlterField(
            model_name='carowreqgoodsowner',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='carowreqgoodsowner',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است؟'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است؟'),
        ),
    ]
