# Generated by Django 5.0.1 on 2024-01-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0003_carowreqdriver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowreqdriver',
            name='proposed_price',
            field=models.FloatField(default='0.0', verbose_name='قیمت پیشنهادی'),
        ),
    ]
