# Generated by Django 5.0.1 on 2024-02-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0004_alter_carowreqdriver_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadfleet',
            name='vehichleTypeOthers',
            field=models.CharField(default='', max_length=100, verbose_name='سایر'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='HeavyVehichle',
            field=models.CharField(choices=[('تریلی', 'تریلی'), ('ترانزیت', 'ترانزیت'), ('ده تن', 'ده تن'), ('کفی', 'کفی'), ('ترانزیت یخچالی', 'ترانزیت یخچالی'), ('بیست تن', 'بیست تن'), ('چادری سه محور', 'چادری سه محور'), ('کمپرسی', 'کمپرسی'), ('تریلی تانکر فاو', 'تریلی تانکر فاو'), ('سایر', 'سایر')], default='', max_length=20, verbose_name='ماشین باربری سنگین'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='semiHeavyVehichle',
            field=models.CharField(choices=[('کامیون', 'کامیون'), ('خاور', 'خاور'), ('هیوندا', 'هیوندا'), ('ماشین باربری ایسوزو', 'ماشین باربری ایسوزو'), ('کامیونت', 'کامیونت'), ('سایر', 'سایر')], default='', max_length=20, verbose_name='ماشین باربری نیمه سنگین'),
        ),
    ]
