# Generated by Django 5.0.1 on 2024-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0004_alter_carowreqdriver_is_changeable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowreqgoodsowner',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو درخواست'),
        ),
    ]
