# Generated by Django 5.0.1 on 2024-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0005_carowreqgoodsowner_cancellation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowreqdriver',
            name='cancellation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو درخواست'),
        ),
    ]
