# Generated by Django 5.0.1 on 2024-01-27 07:36

import goods_owner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0005_alter_carowreqdriver_proposed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowreqdriver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='carowreqdriver',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف'),
        ),
        migrations.AddField(
            model_name='carowreqdriver',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است ؟'),
        ),
        migrations.AddField(
            model_name='carowreqdriver',
            name='is_ok',
            field=models.BooleanField(default=False, verbose_name='آیا تایید شده است؟'),
        ),
        migrations.AlterField(
            model_name='carowreqdriver',
            name='id',
            field=models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
