# Generated by Django 5.0.1 on 2024-01-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0006_carowreqdriver_created_at_carowreqdriver_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowreqdriver',
            name='carrier_owner',
        ),
        migrations.AddField(
            model_name='carowreqdriver',
            name='carrier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carrier_owner.roadfleet', verbose_name='حمل کننده'),
            preserve_default=False,
        ),
    ]
