# Generated by Django 5.0.1 on 2024-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0007_remove_carowreqdriver_carrier_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadfleet',
            name='international_docs',
            field=models.ImageField(blank=True, default='', max_length=800, null=True, upload_to='', verbose_name='آپلود مدارک مجوز حمل بین المللی در صورت وجود'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='owner_document',
            field=models.ImageField(blank=True, default='', max_length=800, null=True, upload_to='', verbose_name='آپلود کارت ملی / پاسپورت مالک'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='vehicle_advocate',
            field=models.ImageField(blank=True, default='', max_length=800, null=True, upload_to='', verbose_name='آپلود بیمه نامه ماشین'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='vehicle_card',
            field=models.ImageField(blank=True, default='', max_length=800, null=True, upload_to='', verbose_name='آپلود کارت ماشین'),
        ),
        migrations.AlterField(
            model_name='roadfleet',
            name='vehicle_property_doc',
            field=models.ImageField(blank=True, default='', max_length=800, null=True, upload_to='', verbose_name='آپلود برگه سبز ماشین'),
        ),
    ]
