# Generated by Django 5.0.1 on 2024-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0009_remove_carowreqdriver_goods_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowreqdriver',
            name='collaboration_type',
            field=models.CharField(choices=[('همکاری دائم (تمام وقت)', 'همکاری دائم (تمام وقت)'), ('همکاری موقت (پاره وقت)', 'همکاری موقت (پاره وقت)')], max_length=40, verbose_name='نوع همکاری'),
        ),
    ]
