# Generated by Django 5.0.1 on 2024-01-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0010_alter_carowreqdriver_collaboration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowreqdriver',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است ؟'),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است ؟'),
        ),
    ]
