# Generated by Django 5.0.1 on 2024-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0011_carowreqdriver_is_deletable_roadfleet_is_deletable'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadfleet',
            name='international_docs_bool',
            field=models.BooleanField(default=False, verbose_name='آپلود مدارک مجوز حمل بین المللی در صورت وجود'),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='vehicle_advocate_bool',
            field=models.BooleanField(default=False, verbose_name='آپلود بیمه نامه ماشین'),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='vehicle_card_bool',
            field=models.BooleanField(default=False, verbose_name='آپلود کارت ماشین'),
        ),
        migrations.AddField(
            model_name='roadfleet',
            name='vehicle_property_doc_bool',
            field=models.BooleanField(default=False, verbose_name='آپلود برگه سبز ماشین'),
        ),
    ]
