# Generated by Django 5.0.1 on 2024-03-01 11:39

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('carrier_owner', '0003_remove_carowreqgoodsowner_carrier_owner_and_more'),
        ('goods_owner', '0012_delete_goodsownerreqcarow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentCollaborationRequestToGoodsOwner',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت پیشنهادی')),
                ('request_result', models.CharField(choices=[('در انتظار پاسخ', 'در انتظار پاسخ'), ('تایید شده', 'تایید شده'), ('رد شده', 'رد شده'), ('لغو شده', 'لغو شده')], max_length=30, verbose_name='نتیجه درخواست')),
                ('cargo_fleet_coordination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_owner.cargofleetcoordination', verbose_name='ماشین های مورد نیاز اعلام بار ماشینی(جدول ارتباطات)')),
                ('carrier_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carrierowner', verbose_name='صاحب حمل کننده')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('goods_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='پروفایل صاحب بار')),
                ('required_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredcarrier', verbose_name='ماشین مورد نیاز اعلام بار')),
                ('road_fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier_owner.roadfleet', verbose_name='حمل کننده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست همکاری صاحب حمل کننده برای اعلام بار ماشینی',
                'verbose_name_plural': 'درخواست های همکاری صاحب حمل کننده برای اعلام بار ماشینی',
            },
        ),
    ]
