# Generated by Django 5.0.1 on 2024-03-03 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driver_type_of_cooperation'),
        ('carrier_owner_req', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentcollaborationrequesttodriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver', verbose_name='راننده'),
        ),
        migrations.AlterField(
            model_name='sentcollaborationrequesttodriver',
            name='request_type',
            field=models.CharField(choices=[('دائم', 'دائم'), ('موقت', 'موقت')], max_length=20, verbose_name='نوع درخواست'),
        ),
    ]
