# Generated by Django 5.0.1 on 2024-03-02 09:04

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('carrier_owner', '0003_remove_carowreqgoodsowner_carrier_owner_and_more'),
        ('carrier_owner_req', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentCollaborationRequestToDriver',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('request_type', models.CharField(choices=[('دائمی', 'دائمی'), ('موقت', 'موقت')], max_length=20, verbose_name='نوع درخواست')),
                ('source_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مبدا بار')),
                ('destination_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقصد بار')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت پیشنهادی')),
                ('request_result', models.CharField(choices=[('در انتظار پاسخ', 'در انتظار پاسخ'), ('تایید شده', 'تایید شده'), ('رد شده', 'رد شده'), ('لغو شده', 'لغو شده')], max_length=30, verbose_name='نتیجه درخواست')),
                ('estimated_loading_time_at_source', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت حدودی بارگیری در مبدا')),
                ('estimated_delivery_time_at_destination', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت حدودی تحویل بار در مقصد')),
                ('carrier_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carrierowner', verbose_name='صاحب حمل کننده')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.driver')),
                ('road_fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrier_owner.roadfleet', verbose_name='حمل کننده')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست همکاری صاحب حمل کننده برای راننده',
                'verbose_name_plural': 'درخواست های همکاری صاحب حمل کننده برای راننده ',
            },
        ),
    ]
