# Generated by Django 5.0.1 on 2024-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innercargo',
            name='bulk_cargo_tonnage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='تناژ خرده بار'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='customs_hs_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد HS گمرکی'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='is_bulk_cargo',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما خرده بار است؟'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='is_hazardous',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما خطرناک است؟'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما فسادپذیر است؟'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='is_plannable',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما قابلیت برنامه\u200cریزی دارد؟'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='refrigeration_temperature',
            field=models.FloatField(default=0, verbose_name='دمای سردخانه'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='un_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد UN (کد کالای خطرناک)'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='weekly_days',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='روزهای هفته'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='bulk_cargo_tonnage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='تناژ خرده بار'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='customs_hs_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد HS گمرکی'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='is_bulk_cargo',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما خرده بار است؟'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='is_hazardous',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما خطرناک است؟'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='is_perishable',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما فسادپذیر است؟'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='is_plannable',
            field=models.BooleanField(default=False, verbose_name='آیا بار شما قابلیت برنامه\u200cریزی دارد؟'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='refrigeration_temperature',
            field=models.FloatField(default=0, verbose_name='دمای سردخانه'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='un_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد UN (کد کالای خطرناک)'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='weekly_days',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='روزهای هفته'),
        ),
    ]
