# Generated by Django 5.0.1 on 2024-02-24 06:16

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_wallet'),
        ('goods_owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoDeclaration',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('relinquished', models.BooleanField(default=False, verbose_name='واگذار شده؟')),
                ('cargo_type', models.CharField(choices=[('اعلام بار داخلی', 'اعلام بار داخلی'), ('اعلام بار خارجی', 'اعلام بار خارجی'), ('اعلام بار ریلی', 'اعلام بار ریلی')], max_length=20, verbose_name='نوع بار')),
                ('net_weight', models.FloatField(verbose_name='وزن خالص محموله')),
                ('special_features', models.TextField(verbose_name='ویژگی\u200cهای خاص مورد نیاز')),
                ('approximate_transport_price', models.FloatField(verbose_name='قیمت تقریبی حمل')),
                ('value_per_wagon', models.FloatField(verbose_name='ارزش بار هر واگن')),
                ('wagon_type', models.CharField(choices=[('short_edge', 'لبه کوتاه'), ('tall_edge', 'لبه بلند'), ('covered', 'مسقف'), ('flatbed', 'مسطح یا پلتفرم'), ('open_roof', 'روباز'), ('bulk', 'فله بر'), ('refrigerated', 'یخچال دار'), ('tanker', 'مخزن دار'), ('sand_carrier', 'شن کش'), ('car_transport', 'حمل خودرو')], max_length=20, verbose_name='نوع واگن')),
                ('route_code', models.CharField(max_length=50, verbose_name='کد مسیر')),
                ('station_code', models.CharField(max_length=50, verbose_name='کد ایستگاه')),
                ('is_plannable', models.BooleanField(default=False, verbose_name='آیا بار قابل برنامه\u200cریزی است؟')),
                ('tonnage_per_shift', models.FloatField(verbose_name='تناژ در هر نوبت')),
                ('is_partial_cargo', models.BooleanField(default=False, verbose_name='آیا بار خرده بار است؟')),
                ('tonnage', models.FloatField(verbose_name='تناژ')),
                ('cargo_type_char_field', models.CharField(max_length=255, verbose_name='نوع بار')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('goods_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner')),
                ('inner_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inner_cargo_carriers_%(class)s_set', to='goods_owner.innercargo', verbose_name='اعلام بار داخلی')),
                ('international_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_cargo_carriers_%(class)s_set', to='goods_owner.internationalcargo', verbose_name='اعلام بار خارجی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
