# Generated by Django 5.0.1 on 2024-03-05 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='railcargo',
            name='approval_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و ساعت تایید یا رد'),
        ),
        migrations.AddField(
            model_name='railcargo',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('تایید شده', 'تایید شده'), ('رد شده', 'رد شده')], max_length=20, null=True, verbose_name='تایید یا رد توسط اتحادیه صادرکنندگان'),
        ),
        migrations.AddField(
            model_name='railcargo',
            name='approved_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rejected_wagons', to=settings.AUTH_USER_MODEL, verbose_name='تایید یا رد توسط کاربر'),
        ),
        migrations.AddField(
            model_name='railcargo',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='شرح دلیل رد شدن درخواست'),
        ),
    ]
