# Generated by Django 5.0.1 on 2024-02-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredcarrier',
            name='cargo_weight',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='وزن خالص محموله'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='counter',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد حمل کننده مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='heavy_vehichle',
            field=models.CharField(blank=True, choices=[('تریلی', 'تریلی'), ('ترانزیت', 'ترانزیت'), ('ده تن', 'ده تن'), ('کفی', 'کفی'), ('ترانزیت یخچالی', 'ترانزیت یخچالی'), ('بیست تن', 'بیست تن'), ('چادری سه محور', 'چادری سه محور'), ('کمپرسی', 'کمپرسی'), ('تریلی تانکر فاو', 'تریلی تانکر فاو')], max_length=20, null=True, verbose_name='ماشین باربری سنگین'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='room_type',
            field=models.CharField(blank=True, choices=[('چادری', 'چادری'), ('روباز', 'روباز'), ('یخچالی', 'یخچالی')], max_length=100, null=True, verbose_name='نوع اتاق مناسب'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='semi_heavy_vehichle',
            field=models.CharField(blank=True, choices=[('کامیون', 'کامیون'), ('خاور', 'خاور'), ('هیوندا', 'هیوندا'), ('ماشین باربری ایسوزو', 'ماشین باربری ایسوزو'), ('کامیونت', 'کامیونت')], max_length=20, null=True, verbose_name='ماشین باربری نیمه سنگین '),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='semi_heavy_vehichle_others',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='سایر'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='vehichle_type',
            field=models.CharField(blank=True, choices=[('ماشین باربری کوچک و سبک', 'ماشین باربری کوچک و سبک'), ('ماشین باربری نیمه سنگین', 'ماشین باربری نیمه سنگین'), ('ماشین حمل بار سنگین', 'ماشین حمل بار سنگین')], max_length=100, null=True, verbose_name='نوع وسیله حمل کننده مورد نیاز'),
        ),
    ]
