# Generated by Django 5.0.1 on 2024-02-25 06:33

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0002_initial'),
        ('goods_owner', '0002_innercargo_bulk_cargo_tonnage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFleetCoordination',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('status_result', models.CharField(choices=[('واگذار شده', 'وارگذار شده'), ('در انتظار واگذاری', 'در انتظار واگذاری')], default='در انتظار واگذاری', max_length=100, verbose_name='وضعیت نتیجه')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('inner_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.innercargo', verbose_name='اعلام بار داخلی')),
                ('international_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.internationalcargo', verbose_name='اعلام بار خارجی')),
                ('required_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredcarrier', verbose_name='حمل کننده ی مورد نیاز اعلام بار')),
                ('road_fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_owner.roadfleet', verbose_name='حمل کننده')),
            ],
            options={
                'verbose_name': 'ماشین  مورد نیاز و ارتباطات',
                'verbose_name_plural': 'ماشین های مورد نیاز و ارتباطات',
            },
        ),
    ]
