# Generated by Django 5.0.1 on 2024-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0002_cargodeclaration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargodeclaration',
            options={'verbose_name': 'واگن  مورد نیاز اعلام بار', 'verbose_name_plural': 'واگن های مورد نیاز اعلام بار'},
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_area',
            field=models.CharField(blank=True, choices=[('گمرگ', 'گمرگ'), ('بندر', 'بندر'), ('ایستگاه', 'ایستگاه')], max_length=100, null=True, verbose_name='محدوده مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_area',
            field=models.CharField(blank=True, choices=[('گمرگ', 'گمرگ'), ('بندر', 'بندر'), ('ایستگاه', 'ایستگاه')], max_length=100, null=True, verbose_name='محدوده مقصد'),
        ),
        migrations.AlterField(
            model_name='cargodeclaration',
            name='cargo_type_char_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نوع بار'),
        ),
        migrations.AlterField(
            model_name='cargodeclaration',
            name='tonnage',
            field=models.FloatField(blank=True, null=True, verbose_name='تناژ'),
        ),
        migrations.AlterField(
            model_name='innercargo',
            name='destination_country',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مقصد'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='destination_country',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مقصد'),
        ),
    ]
