# Generated by Django 5.0.1 on 2024-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0002_remove_goodsownerreqcarow_required_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsownerreqcarow',
            name='required_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.Model, to='goods_owner.requiredcarrier', verbose_name='درخواست حمل کننده'),
        ),
    ]
