# Generated by Django 5.0.1 on 2024-01-30 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_carrierowner_options_and_more'),
        ('goods_owner', '0002_alter_innercargo_is_ok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innercargo',
            name='goods_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='پروفایل صاحب بار'),
        ),
        migrations.AlterField(
            model_name='innercargo',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='innercargo',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است؟'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='goods_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='پروفایل صاحب بار'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است؟'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='is_deletable',
            field=models.BooleanField(default=True, verbose_name='قابل حذف است؟'),
        ),
    ]
