# Generated by Django 5.0.1 on 2024-01-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0002_innercargo_is_deletable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredcarrier',
            name='relinquished',
            field=models.BooleanField(default=False, verbose_name='واگذار شده؟'),
        ),
    ]
