# Generated by Django 5.0.1 on 2024-03-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0002_railcargo_approval_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railcargo',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('در انتظار پاسخ', 'در انتظار پاسخ'), ('تایید شده', 'تایید شده'), ('رد شده', 'رد شده')], default='در انتظار پاسخ', max_length=20, null=True, verbose_name='تایید یا رد توسط اتحادیه صادرکنندگان'),
        ),
    ]
