# Generated by Django 5.0.1 on 2024-02-01 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('goods_owner', '0002_alter_requiredcarrier_cargo_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredcarrier',
            name='goods_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='صاحب بار'),
        ),
    ]
