# Generated by Django 5.0.1 on 2024-03-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0003_alter_railcargo_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='railcargo',
            name='destination_area',
            field=models.CharField(blank=True, choices=[('گمرک', 'گمرک'), ('بندر', 'بندر'), ('ایستگاه', 'ایستگاه'), ('گمرک/ایستگاه', 'گمرک/ایستگاه')], max_length=100, null=True, verbose_name='محدوده مقصد'),
        ),
    ]
