# Generated by Django 5.0.1 on 2024-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0003_requiredcarrier_relinquished'),
    ]

    operations = [
        migrations.AddField(
            model_name='innercargo',
            name='cargo_receiver_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='cargo_receiver_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل مدیر عامل تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='cargo_receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='cargo_receiver_national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='delivery_provider_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='delivery_provider_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل مدیر عامل تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='delivery_provider_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='delivery_provider_national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_receiver_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_receiver_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل مدیر عامل تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_receiver_national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='delivery_provider_full_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='delivery_provider_mobile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل مدیر عامل تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='delivery_provider_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت تحویل دهنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='delivery_provider_national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی تحویل دهنده'),
        ),
    ]
