# Generated by Django 5.0.1 on 2024-02-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0003_goodsownerreqcarow_required_carrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsownerreqcarow',
            name='required_carrier',
        ),
    ]
