# Generated by Django 5.0.1 on 2024-01-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0004_innercargo_cargo_receiver_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalcargo',
            name='senderCountry',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('7افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=255, null=True, verbose_name='کشور مبدا'),
        ),
    ]
