# Generated by Django 5.0.1 on 2024-02-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0004_remove_innercargo_basculprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innercargo',
            name='is_perishable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا بار شما فسادپذیر است؟'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='is_perishable',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا بار شما فسادپذیر است؟'),
        ),
    ]
