# Generated by Django 5.0.1 on 2024-02-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('goods_owner', '0005_goodsownerreqcarow_inner_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsownerreqcarow',
            name='carrier_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrier_owner_requests', to='accounts.carrierowner', verbose_name='صاحب  حمل کننده'),
        ),
        migrations.AlterField(
            model_name='goodsownerreqcarow',
            name='goods_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_owner_requests', to='accounts.goodsowner', verbose_name='صاحب بار'),
        ),
        migrations.AlterField(
            model_name='goodsownerreqcarow',
            name='proposed_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='قیمت پیشنهادی'),
        ),
    ]
