# Generated by Django 5.0.1 on 2024-02-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0005_alter_innercargo_is_perishable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requiredcarrier',
            name='heavy_vehichle',
        ),
        migrations.RemoveField(
            model_name='requiredcarrier',
            name='heavy_vehichle_others',
        ),
        migrations.RemoveField(
            model_name='requiredcarrier',
            name='semi_heavy_vehichle',
        ),
        migrations.RemoveField(
            model_name='requiredcarrier',
            name='semi_heavy_vehichle_others',
        ),
        migrations.AddField(
            model_name='innercargo',
            name='cargo_procedure_type',
            field=models.CharField(blank=True, choices=[('صادراتی', 'صادراتی'), ('وارداتی', 'وارداتی'), ('ترانزیتی', 'ترانزیتی')], max_length=20, null=True, verbose_name='نوع رویه بار'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_procedure_type',
            field=models.CharField(blank=True, choices=[('صادراتی', 'صادراتی'), ('وارداتی', 'وارداتی'), ('ترانزیتی', 'ترانزیتی')], max_length=20, null=True, verbose_name='نوع رویه بار'),
        ),
        migrations.AlterField(
            model_name='innercargo',
            name='country',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مبدا'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='country',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مبدا'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='senderCountry',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=255, null=True, verbose_name='کشور مبدا'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='room_type',
            field=models.CharField(blank=True, choices=[('چادری', 'چادری'), ('روباز', 'روباز'), ('یخچالی', 'یخچالی'), ('کمپرسی', 'کمپرسی'), ('مسقف', 'مسقف'), ('کفی', 'کفی'), ('بفل دار', 'بقل دار')], max_length=100, null=True, verbose_name='نوع اتاق مناسب'),
        ),
        migrations.AlterField(
            model_name='requiredcarrier',
            name='vehichle_type',
            field=models.CharField(blank=True, choices=[('تریلی', 'تریلی'), ('جفت', 'جفت'), ('تک', 'تک'), ('خاور', 'خاور'), ('وانت و نیسان', 'وانت ونیسان'), ('خاور', 'خاور')], max_length=100, null=True, verbose_name='نوع وسیله حمل کننده مورد نیاز'),
        ),
    ]
