# Generated by Django 5.0.1 on 2024-02-25 14:26

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('goods_owner', '0006_remove_requiredcarrier_heavy_vehichle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='innercargo',
            name='need_route_code',
            field=models.BooleanField(default=False, verbose_name='آیا نیاز به کد مسیر دارید؟'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='route_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد مسیر'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='need_route_code',
            field=models.BooleanField(default=False, verbose_name='آیا نیاز به کد مسیر دارید؟'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='route_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد مسیر'),
        ),
        migrations.CreateModel(
            name='RequiredWagons',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('relinquished', models.BooleanField(default=False, verbose_name='واگذار شده؟')),
                ('cargo_type', models.CharField(choices=[('اعلام بار داخلی', 'اعلام بار داخلی'), ('اعلام بار خارجی', 'اعلام بار خارجی'), ('اعلام بار ریلی', 'اعلام بار ریلی')], max_length=20, verbose_name='نوع بار')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('goods_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner')),
                ('inner_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagon_inner_cargo_carriers', to='goods_owner.innercargo', verbose_name='اعلام بار داخلی')),
                ('international_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wagon_international_cargo_carriers', to='goods_owner.internationalcargo', verbose_name='اعلام بار خارجی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
