# Generated by Django 5.0.1 on 2024-02-26 09:21

import datetime
import django.db.models.deletion
import django.utils.timezone
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('goods_owner', '0007_innercargo_need_route_code_innercargo_route_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredwagons',
            name='capacity',
            field=models.CharField(blank=True, choices=[('واگن 24', 'واگن 24'), ('واگن 26', 'واگن 26'), ('واگن 28', 'واگن 28'), ('واگن 29', 'واگن 29'), ('سایر', 'سایر')], default='', max_length=20, null=True, verbose_name='ظرفیت حمل'),
        ),
        migrations.AddField(
            model_name='requiredwagons',
            name='net_weight',
            field=models.FloatField(default=1, verbose_name='وزن خالص محموله'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requiredwagons',
            name='wagon_type',
            field=models.CharField(blank=True, choices=[('مسقف', 'مسقف'), ('فله بر', 'فله بر'), ('مسطح', 'مسطح'), ('یخچال دار', 'یخچال دار'), ('مخزن دار', 'مخزن دار'), ('لبه بلند', 'لبه بلند'), ('لبه کوتاه', 'لبه کوتاه'), ('حمل خودرو', 'حمل خودرو')], max_length=20, null=True, verbose_name='نوع واگن'),
        ),
        migrations.CreateModel(
            name='RailCargo',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('length', models.IntegerField(blank=True, default=0, null=True, verbose_name='طول')),
                ('width', models.IntegerField(blank=True, default=0, null=True, verbose_name='عرض')),
                ('height', models.IntegerField(blank=True, default=0, null=True, verbose_name='ارتفاع')),
                ('cargoType', models.CharField(blank=True, default='', max_length=800, null=True, verbose_name='عنوان محموله')),
                ('pkgType', models.CharField(blank=True, choices=[('کیسه', 'کیسه'), ('فله', 'فله'), ('پالت', 'پالت'), ('جامبو', 'جامبو'), ('کانتینر', 'کانتینر'), ('بندی', 'بندی'), ('رول', 'رول'), ('سواری', 'سواری'), ('جعبه', 'جعبه'), ('کالای خاص', 'کالای خاص'), ('غیر پالیتیزه', 'غیر پالیتیزه'), ('غیرمعمول', 'غیرمعمول')], max_length=20, null=True, verbose_name='نوع بسته بندی')),
                ('description', models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='توضیحات')),
                ('specialDesc', models.TextField(blank=True, default='', max_length=9999, null=True, verbose_name='توضیحات خاص')),
                ('sendersName', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام و نام خانوادگی فرستنده')),
                ('senderMobileNum', models.CharField(blank=True, default='', max_length=12, null=True, verbose_name='شماره تلفن / موبایل فرستنده')),
                ('dischargeTimeDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=200, null=True, verbose_name='حدود تاریخ و ساعت تحویل بار در مقصد')),
                ('duratio_ndischargeTime', models.DurationField(blank=True, default=datetime.timedelta(0), max_length=200, null=True, verbose_name=' مدت زمان تخلیه بار در مقصد')),
                ('delivery_provider_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت تحویل دهنده')),
                ('delivery_provider_national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی تحویل دهنده')),
                ('delivery_provider_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی تحویل دهنده')),
                ('delivery_provider_mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل مدیر عامل تحویل دهنده')),
                ('cargo_receiver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام شرکت تحویل گیرنده')),
                ('cargo_receiver_national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی تحویل گیرنده')),
                ('cargo_receiver_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی تحویل گیرنده')),
                ('cargo_receiver_mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل مدیر عامل تحویل گیرنده')),
                ('country', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مبدا')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='استان مبدا')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر / منطقه / محدوده مبدا')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='خیابان مبدا')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس دقیق مبدا')),
                ('customName', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام کمرگ مبدا')),
                ('cargo_receiver_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی تحویل گیرنده')),
                ('destination_country', models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مقصد')),
                ('destination_state', models.CharField(blank=True, max_length=20, null=True, verbose_name='استان مقصد')),
                ('destination_city', models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر / منطقه / محدوده مقصد')),
                ('destination_street', models.CharField(blank=True, max_length=50, null=True, verbose_name='خیابان مقصد')),
                ('destination_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس دقیق مقصد')),
                ('destination_area', models.CharField(blank=True, choices=[('گمرگ', 'گمرگ'), ('بندر', 'بندر'), ('ایستگاه', 'ایستگاه'), ('گمرک/ایستگاه', 'گمرک/ایستگاه')], max_length=100, null=True, verbose_name='محدوده مقصد')),
                ('destination_custom_name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام  مقصد')),
                ('is_bulk_cargo', models.BooleanField(default=False, verbose_name='آیا بار شما خرده بار است؟')),
                ('bulk_cargo_tonnage', models.FloatField(blank=True, default=0, null=True, verbose_name='تناژ خرده بار')),
                ('is_plannable', models.BooleanField(default=False, verbose_name='آیا بار شما قابلیت برنامه\u200cریزی دارد؟')),
                ('weekly_days', models.CharField(blank=True, max_length=100, null=True, verbose_name='روزهای هفته')),
                ('is_perishable', models.BooleanField(blank=True, default=False, null=True, verbose_name='آیا بار شما فسادپذیر است؟')),
                ('refrigeration_temperature', models.FloatField(default=0, verbose_name='دمای سردخانه')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='آیا بار شما خطرناک است؟')),
                ('un_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد UN (کد کالای خطرناک)')),
                ('customs_hs_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد HS گمرکی')),
                ('pallet_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='سایز پالت (مشخصات بسته بندی)')),
                ('pallet_arrangement_type', models.CharField(blank=True, choices=[('کف', 'کف'), ('طبقاتی', 'طبقاتی')], max_length=50, null=True, verbose_name='نوع چیدمان پالت')),
                ('approximate_weight_per_packaging', models.FloatField(blank=True, null=True, verbose_name='وزن حدودی هر یک بسته بندی')),
                ('is_all_cargo_type', models.BooleanField(default=False, verbose_name='آیا تمام بار تیپ است؟')),
                ('approximate_weight_per_type', models.FloatField(blank=True, null=True, verbose_name='وزن حدودی هر تیپ')),
                ('specialized_lashing_required', models.BooleanField(default=False, verbose_name='آیا بار نیاز به مهار بندی تخصصی دارد؟')),
                ('specialized_lashing_type_upload', models.ImageField(blank=True, null=True, upload_to='lashing_types/', verbose_name='آپلود نوع مهار بندی تخصصی')),
                ('specialized_lashing_type_description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='توضیح نوع مهار بندی تخصصی')),
                ('need_warehouse', models.BooleanField(default=False, verbose_name='آیا نیاز به انبار دارید؟')),
                ('warehouse_duration', models.DurationField(blank=True, null=True, verbose_name='مدت زمان انبار داری')),
                ('sender_additional_requests', models.TextField(blank=True, max_length=5000, null=True, verbose_name='درخواست های تکمیلی فرستنده')),
                ('cargo_procedure_type', models.CharField(blank=True, choices=[('صادراتی', 'صادراتی'), ('وارداتی', 'وارداتی'), ('ترانزیتی', 'ترانزیتی')], max_length=20, null=True, verbose_name='نوع رویه بار')),
                ('need_route_code', models.BooleanField(default=False, verbose_name='آیا نیاز به کد مسیر دارید؟')),
                ('route_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد مسیر')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('goods_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='پروفایل صاحب بار')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلام بار ریلی',
                'verbose_name_plural': 'اعلام بار های ریلی',
            },
        ),
        migrations.DeleteModel(
            name='CargoDeclaration',
        ),
    ]
