# Generated by Django 5.0.1 on 2024-02-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0007_alter_goodsownerreqcarow_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='innercargo',
            name='cargo_receiver_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس دقیق مقصد'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر / منطقه / محدوده مقصد'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کشور مقصد'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_custom_name',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('7افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], default='', max_length=100, null=True, verbose_name='نام کمرگ مقصد'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='استان مقصد'),
        ),
        migrations.AddField(
            model_name='innercargo',
            name='destination_street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خیابان مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_receiver_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام خانوادگی تحویل گیرنده'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='آدرس دقیق مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر / منطقه / محدوده مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_country',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کشور مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_custom_name',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('7افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], default='', max_length=100, null=True, verbose_name='نام کمرگ مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='استان مقصد'),
        ),
        migrations.AddField(
            model_name='internationalcargo',
            name='destination_street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='خیابان مقصد'),
        ),
    ]
