# Generated by Django 5.0.1 on 2024-02-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0008_innercargo_cargo_receiver_surname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalcargo',
            name='cargo_weight',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='وزن خالص محموله'),
        ),
        migrations.AlterField(
            model_name='innercargo',
            name='destination_country',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('7افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مقصد'),
        ),
        migrations.AlterField(
            model_name='innercargo',
            name='destination_custom_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام کمرگ مقصد'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='destination_country',
            field=models.CharField(blank=True, choices=[('ایران', 'ایران'), ('روسیه', 'روسیه'), ('قزاقستان', 'قزاقستان'), ('ازبکستان', 'ازبکستان'), ('قرقیزستان', 'قرقیزستان'), ('تاجیکستان', 'تاجیکستان'), ('7افغانستان', 'افغانستان'), ('ارمنستان', 'ارمنستان')], max_length=20, null=True, verbose_name='کشور مقصد'),
        ),
        migrations.AlterField(
            model_name='internationalcargo',
            name='destination_custom_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='نام کمرگ مقصد'),
        ),
    ]
