# Generated by Django 5.0.1 on 2024-02-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('goods_owner', '0010_cargowagoncoordination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargowagoncoordination',
            options={'verbose_name': 'واگن  مورد نیاز و ارتباطات', 'verbose_name_plural': 'واگن  های مورد نیاز و ارتباطات'},
        ),
        migrations.AlterField(
            model_name='cargowagoncoordination',
            name='required_wagons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredwagons', verbose_name='واگن مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='cargowagoncoordination',
            name='wagon_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.wagonowner', verbose_name='صاحب واگن'),
        ),
    ]
