# Generated by Django 5.0.1 on 2024-02-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0011_alter_cargowagoncoordination_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoodsOwnerReqCarOw',
        ),
    ]
