# Generated by Django 5.0 on 2024-01-20 12:55

import carrier_owner.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverReqToCarrier',
            fields=[
                ('id', models.CharField(default=carrier_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('cargo_type', models.CharField(choices=[('inner_cargo', 'اعلام بار داخلی'), ('international_cargo', 'اعلام بار خارجی'), ('rail_cargo', 'اعلام بار ریلی')], default='inner_cargo', max_length=20, verbose_name='نوع همکاری')),
                ('price', models.FloatField(default=0, verbose_name='قیمت پیشنهادی')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='مبدا راننده')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.carrierowner', verbose_name='صاحب حمل کننده')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests_to_carriers', to=settings.AUTH_USER_MODEL, verbose_name='راننده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
