# Generated by Django 5.0.1 on 2024-03-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverReqCarrierOwner',
        ),
    ]
