# Generated by Django 5.0.1 on 2024-02-24 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier_owner', '0003_alter_roadfleet_carrier_type'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverreqcarrierowner',
            name='carrier_owner',
        ),
        migrations.AddField(
            model_name='driverreqcarrierowner',
            name='road_fleet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrier_owner.roadfleet', verbose_name='حمل کننده'),
        ),
    ]
