# Generated by Django 5.0.1 on 2024-02-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_driver_address_driver_health_card_expiry_date_and_more'),
        ('driver', '0002_remove_driverreqcarrierowner_carrier_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverreqcarrierowner',
            name='road_fleet',
        ),
        migrations.AddField(
            model_name='driverreqcarrierowner',
            name='carrier_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carrierowner', verbose_name='صاحب حمل کننده'),
        ),
    ]
