# Generated by Django 5.0.1 on 2024-02-28 08:56

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('goods_owner', '0011_alter_cargowagoncoordination_options_and_more'),
        ('wagon_owner', '0003_alter_wagondetails_wagon_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentCollaborationRequestToRailCargo',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت پیشنهادی')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('rail_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.railcargo', verbose_name='اعلام بار ریلی')),
                ('required_wagons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredwagons', verbose_name='واگن مورد نیاز')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wagon_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagon_owner.wagondetails', verbose_name='واگن')),
                ('wagon_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.wagonowner', verbose_name='صاحب واگن')),
            ],
            options={
                'verbose_name': 'درخواست همکاری صاحب واگن برای اعلام بار ریلی',
                'verbose_name_plural': 'درخواست\u200cهای همکاری صاحب واگن برای اعلام بار ریلی',
            },
        ),
    ]
