# Generated by Django 5.0.1 on 2024-03-06 06:16

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('goods_owner', '0001_initial'),
        ('wagon_owner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentCollaborationRequestToRailCargo',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('proposed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت پیشنهادی')),
                ('request_result', models.CharField(choices=[('در انتظار پاسخ', 'در انتظار پاسخ'), ('تایید شده', 'تایید شده'), ('رد شده', 'رد شده'), ('لغو شده', 'لغو شده')], max_length=30, verbose_name='نتیجه درخواست')),
                ('cargo_wagon_coordination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.cargowagoncoordination', verbose_name='واگن های مورد نیاز اعلام بار ریلی(جدول  ارتباطات)')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
                ('goods_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.goodsowner', verbose_name='پروفایل صاحب بار')),
                ('rail_cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.railcargo', verbose_name='اعلام بار ریلی')),
                ('required_wagons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredwagons', verbose_name='واگن های مورد نیاز اعلام بار ریلی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('wagon_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagon_owner.wagondetails', verbose_name='واگن های تعریف شده ی صاحب واگن')),
                ('wagon_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.wagonowner', verbose_name='پروفایل صاحب واگن')),
            ],
            options={
                'verbose_name': 'درخواست همکاری صاحب واگن برای اعلام بار ریلی',
                'verbose_name_plural': 'درخواست\u200cهای همکاری صاحب واگن برای اعلام بار ریلی',
            },
        ),
    ]
