# Generated by Django 5.0.1 on 2024-02-28 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_owner', '0012_delete_goodsownerreqcarow'),
        ('wagon_owner_req', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentcollaborationrequesttorailcargo',
            name='cargo_wagon_coordination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.cargowagoncoordination', verbose_name='واگن های مورد نیاز'),
        ),
        migrations.AlterField(
            model_name='sentcollaborationrequesttorailcargo',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='sentcollaborationrequesttorailcargo',
            name='required_wagons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredwagons', verbose_name='اعلام نیاز واگن برای بار ریلی'),
        ),
    ]
