# Generated by Django 5.0.1 on 2024-02-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_user_type_wagonowner'),
        ('goods_owner', '0012_delete_goodsownerreqcarow'),
        ('wagon_owner', '0003_alter_wagondetails_wagon_counts'),
        ('wagon_owner_req', '0003_sentcollaborationrequesttorailcargo_goods_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentcollaborationrequesttorailcargo',
            name='cargo_wagon_coordination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.cargowagoncoordination', verbose_name='واگن های مورد نیاز اعلام بار ریلی(جدول  ارتباطات)'),
        ),
        migrations.AlterField(
            model_name='sentcollaborationrequesttorailcargo',
            name='required_wagons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_owner.requiredwagons', verbose_name='واگن های مورد نیاز اعلام بار ریلی'),
        ),
        migrations.AlterField(
            model_name='sentcollaborationrequesttorailcargo',
            name='wagon_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagon_owner.wagondetails', verbose_name='واگن های تعریف شده ی صاحب واگن'),
        ),
        migrations.AlterField(
            model_name='sentcollaborationrequesttorailcargo',
            name='wagon_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.wagonowner', verbose_name='پروفایل صاحب واگن'),
        ),
    ]
