# Generated by Django 5.0.1 on 2024-02-24 13:47

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierOwner',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('car_card_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس کارت ماشین')),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس بیمه نامه')),
                ('green_sheet_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس برگه سبز')),
                ('national_code_or_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی یا پاسپورت صاحب ماشین')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس کارت ملی یا پاسپورت')),
                ('owner_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی صاحب ماشین')),
                ('owner_mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل صاحب ماشین')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت حمل\u200cکننده')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی صاحب حمل\u200cکننده')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('nationality', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملیت')),
                ('legal_status', models.CharField(blank=True, choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], max_length=20, null=True, verbose_name='وضعیت حقوقی')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صاحب حمل\u200cکننده',
                'verbose_name_plural': 'صاحبان حمل\u200cکننده',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=False, verbose_name='قابل تغییر است؟')),
                ('driver_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی راننده')),
                ('national_card_or_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی یا پاسپورت راننده')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='عکس کارت ملی یا پاسپورت')),
                ('national_card_image_bool', models.BooleanField(blank=True, default=False, null=True, verbose_name='عکس کارت ملی یا پاسپورت')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل راننده')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار گواهینامه')),
                ('smart_card_image', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='عکس کارت هوشمند')),
                ('smart_card_image_bool', models.BooleanField(blank=True, default=False, null=True, verbose_name='عکس کارت هوشمند')),
                ('domestic_license', models.BooleanField(blank=True, default=False, null=True, verbose_name='گواهی نامه داخلی')),
                ('international_license', models.BooleanField(blank=True, default=False, null=True, verbose_name='گواهینامه بین المللی')),
                ('international_license_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار گواهینامه بین المللی')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='ادرس')),
                ('health_card_image', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='عکس کارت سلامت')),
                ('health_card_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا کارت سلامت')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
            },
        ),
        migrations.CreateModel(
            name='GoodsOwner',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی صاحب بار / مدیر عامل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='موبایل صاحب بار / مدیر عامل')),
                ('national_code_passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی / شماره پاسپورت')),
                ('national_card_passport_image', models.ImageField(blank=True, null=True, upload_to='goods_owners/', verbose_name='آپلود کارت ملی / پاسپورت')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت')),
                ('national_id_optional', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی (اختیاری در صورت نداشتن شرکت)')),
                ('trade_license_expiry', models.DateField(blank=True, null=True, verbose_name='کارت بازرگانی انقضا')),
                ('trade_license_image', models.ImageField(blank=True, null=True, upload_to='goods_owners/', verbose_name='آپلود کارت بازرگانی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس صاحب بار / شرکت')),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='کدپستی صاحب بار / شرکت')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صاحب بار',
                'verbose_name_plural': 'صاحبان بار',
            },
        ),
        migrations.CreateModel(
            name='PasswordSetStatus',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_password_set', models.BooleanField(default=False, verbose_name='آیا رمز عبور تنظیم شده است؟')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token', verbose_name='توکن')),
            ],
            options={
                'verbose_name': 'وضعیت پسورد',
                'verbose_name_plural': 'وضعیت پسورد کاربر ها',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_completed', models.BooleanField(default=False, verbose_name='پروفایل تکمیل  شده؟')),
                ('is_ok', models.BooleanField(default=False, verbose_name='پروفایل تایید شده؟')),
                ('user_type', models.CharField(choices=[('انتخاب نشده', 'انتخاب نشده'), ('صاحب بار', 'صاحب بار'), ('صاحب حمل کننده', 'صاحب حمل کننده'), ('راننده', 'راننده'), ('ادمین', 'ادمین')], default='انتخاب نشده', max_length=255, verbose_name='نوع کاربر')),
                ('wallet', models.FloatField(blank=True, default=0, null=True, verbose_name='کیف پول')),
                ('unique_code', models.CharField(help_text='کد اختصاصی', max_length=25, unique=True, verbose_name='کد اختصاصی')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('is_valid', models.BooleanField(auto_created=True, default=True, verbose_name='وضعیت اعتبار')),
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('random_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تصادفی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضاء')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق')),
                ('ip', models.CharField(blank=True, max_length=40, null=True, verbose_name='آدرس IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد تایید',
                'verbose_name_plural': 'کد های تایید',
            },
        ),
    ]
