# Generated by Django 5.0.1 on 2024-01-25 17:26

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierOwner',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=False, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('car_card_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس کارت ماشین')),
                ('insurance_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس بیمه نامه')),
                ('green_sheet_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس برگه سبز')),
                ('national_code_or_passport', models.CharField(max_length=20, verbose_name='کد ملی یا پاسپورت صاحب ماشین')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to='carriers/', verbose_name='عکس کارت ملی یا پاسپورت')),
                ('owner_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی صاحب ماشین')),
                ('owner_mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل صاحب ماشین')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صاحب حمل\u200cکننده',
                'verbose_name_plural': ' صاحبان حمل کننده ها',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=False, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('driver_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی راننده')),
                ('national_card_or_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی یا پاسپورت راننده')),
                ('national_card_image', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='عکس کارت ملی یا پاسپورت')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره موبایل راننده')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار گواهینامه')),
                ('smart_card_image', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='عکس کارت هوشمند')),
                ('domestic_license', models.BooleanField(blank=True, default=False, null=True, verbose_name='گواهی نامه داخلی')),
                ('international_license', models.BooleanField(blank=True, default=False, null=True, verbose_name='گواهینامه بین المللی')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'راننده',
                'verbose_name_plural': 'رانندگان',
            },
        ),
        migrations.CreateModel(
            name='GoodsOwner',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=False, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی صاحب بار / مدیر عامل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='موبایل صاحب بار / مدیر عامل')),
                ('national_code_passport_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی / شماره پاسپورت')),
                ('national_card_passport_image', models.ImageField(blank=True, null=True, upload_to='goods_owners/', verbose_name='آپلود کارت ملی / پاسپورت')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت')),
                ('national_id_optional', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی (اختیاری در صورت نداشتن شرکت)')),
                ('trade_license_expiry', models.DateField(blank=True, null=True, verbose_name='کارت بازرگانی انقضا')),
                ('trade_license_image', models.ImageField(blank=True, null=True, upload_to='goods_owners/', verbose_name='آپلود کارت بازرگانی')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس صاحب بار / شرکت')),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='کدپستی صاحب بار / شرکت')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صاحب بار',
                'verbose_name_plural': 'صاحبان بار',
            },
        ),
        migrations.CreateModel(
            name='PasswordSetStatus',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=False, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('is_password_set', models.BooleanField(default=False)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('is_completed', models.BooleanField(default=False, verbose_name='پروفایل تکمیل  شده؟')),
                ('is_ok', models.BooleanField(default=False, verbose_name='پروفایل تایید شده؟')),
                ('user_type', models.CharField(choices=[('انتخاب نشده', 'انتخاب نشده'), ('صاحب بار', 'صاحب بار'), ('صاحب حمل کننده', 'صاحب حمل کننده'), ('راننده', 'راننده')], default='انتخاب نشده', max_length=255, verbose_name='نوع کاربر')),
                ('unique_code', models.CharField(help_text='کد اختصاصی', max_length=25, unique=True, verbose_name='کد اختصاصی')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('is_valid', models.BooleanField(auto_created=True, default=True)),
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=False, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است ؟')),
                ('random_code', models.CharField(blank=True, max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('failed_attempts', models.IntegerField(default=0)),
                ('ip', models.CharField(blank=True, max_length=40, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
