# Generated by Django 5.0.1 on 2024-01-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='driver',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان'),
        ),
    ]
