# Generated by Django 5.0.1 on 2024-01-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('authtoken', '0003_tokenproxy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrierowner',
            options={'verbose_name': 'صاحب حمل\u200cکننده', 'verbose_name_plural': 'صاحبان حمل\u200cکننده'},
        ),
        migrations.AlterField(
            model_name='carrierowner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم'),
        ),
        migrations.AlterField(
            model_name='carrierowner',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='goodsowner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم'),
        ),
        migrations.AlterField(
            model_name='goodsowner',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='passwordsetstatus',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم'),
        ),
        migrations.AlterField(
            model_name='passwordsetstatus',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='passwordsetstatus',
            name='is_password_set',
            field=models.BooleanField(default=False, verbose_name='آیا رمز عبور تنظیم شده است؟'),
        ),
        migrations.AlterField(
            model_name='passwordsetstatus',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token', verbose_name='توکن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='تاریخ انقضاء'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='failed_attempts',
            field=models.IntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='ip',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='آدرس IP'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='is_changeable',
            field=models.BooleanField(default=True, verbose_name='قابل تغییر است؟'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='is_valid',
            field=models.BooleanField(auto_created=True, default=True, verbose_name='وضعیت اعتبار'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='random_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تصادفی'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
