# Generated by Django 5.0.1 on 2024-02-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordsetstatus',
            options={'verbose_name': 'وضعیت پسورد', 'verbose_name_plural': 'وضعیت پسورد کاربر ها'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل ها'},
        ),
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'کد تایید', 'verbose_name_plural': 'کد های تایید'},
        ),
    ]
