# Generated by Django 5.0.1 on 2024-03-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='type_of_cooperation',
            field=models.CharField(blank=True, choices=[('موقت', 'موقت'), ('دائم', 'دائم'), ('موقت و دائم', 'موقت و دائم')], max_length=255, null=True, verbose_name='نوع همکاری'),
        ),
    ]
