# Generated by Django 5.0.1 on 2024-02-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مبدا راننده'),
        ),
        migrations.AddField(
            model_name='driver',
            name='type_of_cooperation',
            field=models.CharField(blank=True, choices=[('موقت', 'موقت'), ('دائم', 'دائم'), ('هردو', 'هردو')], max_length=255, null=True, verbose_name='نوع همکاری'),
        ),
    ]
