# Generated by Django 5.0.1 on 2024-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierowner',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='carrierowner',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت حمل\u200cکننده'),
        ),
        migrations.AddField(
            model_name='carrierowner',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('حقیقی', 'حقیقی'), ('حقوقی', 'حقوقی')], max_length=20, null=True, verbose_name='وضعیت حقوقی'),
        ),
        migrations.AddField(
            model_name='carrierowner',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی صاحب حمل\u200cکننده'),
        ),
        migrations.AddField(
            model_name='carrierowner',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ملیت'),
        ),
    ]
