# Generated by Django 5.0.1 on 2024-02-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_carrierowner_address_carrierowner_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierowner',
            name='national_code_or_passport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی یا پاسپورت صاحب ماشین'),
        ),
    ]
