# Generated by Django 5.0.1 on 2024-02-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_origin_driver_type_of_cooperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='cooperate_with_carrier_owners',
            field=models.BooleanField(default=False, verbose_name='آیا مایل به همکاری با صاحبان حمل کننده می\u200cباشید؟'),
        ),
    ]
