# Generated by Django 5.0.1 on 2024-03-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driver_type_of_cooperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('انتخاب نشده', 'انتخاب نشده'), ('صاحب بار', 'صاحب بار'), ('صاحب حمل کننده', 'صاحب حمل کننده'), ('راننده', 'راننده'), ('صاحب واگن', 'صاحب واگن'), ('ادمین', 'ادمین'), ('اتحادیه صادرکنندگان', 'اتحادیه صادرکنندگان')], default='انتخاب نشده', max_length=255, verbose_name='نوع کاربر'),
        ),
    ]
