# Generated by Django 5.0.1 on 2024-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_city_driver_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='national_card_image_bool',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='عکس کارت ملی یا پاسپورت'),
        ),
        migrations.AddField(
            model_name='driver',
            name='smart_card_image_bool',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='عکس کارت هوشمند'),
        ),
    ]
