# Generated by Django 5.0.1 on 2024-02-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_carrierowner_national_code_or_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='کیف پول'),
        ),
    ]
