# Generated by Django 5.0.1 on 2024-02-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='international_license_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اعتبار گواهینامه بین المللی'),
        ),
    ]
