# Generated by Django 5.0.1 on 2024-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ادرس'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_card_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا کارت سلامت'),
        ),
        migrations.AddField(
            model_name='driver',
            name='health_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='عکس کارت سلامت'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_changeable',
            field=models.BooleanField(default=False, verbose_name='قابل تغییر است؟'),
        ),
    ]
