# Generated by Django 5.0.1 on 2024-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('انتخاب نشده', 'انتخاب نشده'), ('صاحب بار', 'صاحب بار'), ('صاحب حمل کننده', 'صاحب حمل کننده'), ('راننده', 'راننده'), ('ادمین', 'ادمین')], default='انتخاب نشده', max_length=255, verbose_name='نوع کاربر'),
        ),
    ]
