# Generated by Django 5.0.1 on 2024-02-25 14:26

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('انتخاب نشده', 'انتخاب نشده'), ('صاحب بار', 'صاحب بار'), ('صاحب حمل کننده', 'صاحب حمل کننده'), ('راننده', 'راننده'), ('صاحب واگن', 'صاحب واگن'), ('ادمین', 'ادمین')], default='انتخاب نشده', max_length=255, verbose_name='نوع کاربر'),
        ),
        migrations.CreateModel(
            name='WagonOwner',
            fields=[
                ('id', models.CharField(default=accounts.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف نرم')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت')),
                ('ceo_full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام و نام خانوادگی مدیر عامل')),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره موبایل')),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='شناسه ملی')),
                ('ownership_type', models.CharField(blank=True, choices=[('خصوصی', 'خصوصی'), ('دولتی', 'دولتی')], max_length=20, null=True, verbose_name='نوع مالکیت')),
                ('national_code_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد ملی/شماره پاسپورت')),
                ('national_id_passport_image', models.ImageField(blank=True, null=True, upload_to='national_id_passport/', verbose_name='عکس کارت ملی/پاسپورت')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='کشور')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس شرکت')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'صاحب  واگن',
                'verbose_name_plural': 'صاحبان واگن',
            },
        ),
    ]
