# Generated by Django 5.0.1 on 2024-02-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست های وبلاگ'},
        ),
    ]
