# Generated by Django 5.0.1 on 2024-02-24 13:47

import django.db.models.deletion
import goods_owner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInfo',
            fields=[
                ('id', models.CharField(default=goods_owner.models.generate_complex_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='تاریخ حذف')),
                ('is_ok', models.BooleanField(default=True, verbose_name='آیا تایید شده است؟')),
                ('is_changeable', models.BooleanField(default=True, verbose_name='قابل تغییر است؟')),
                ('is_deletable', models.BooleanField(default=True, verbose_name='قابل حذف است؟')),
                ('ready_to_work_drivers', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد راننده\u200cهای آماده به کار')),
                ('distance_covered', models.PositiveIntegerField(blank=True, null=True, verbose_name='کیلومتر مسیر طی شده')),
                ('loads_carried', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد بار حمل شده')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('full_address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('phone_prefix', models.CharField(blank=True, max_length=5, null=True, verbose_name='پیش\u200c شماره')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('working_days', models.CharField(blank=True, max_length=50, null=True, verbose_name='روزهای کاری')),
                ('telegram_address', models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام')),
                ('whatsapp_address', models.URLField(blank=True, null=True, verbose_name='آدرس واتساپ')),
                ('instagram_address', models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام')),
                ('facebook_address', models.URLField(blank=True, null=True, verbose_name='آدرس فیسبوک')),
                ('android_app', models.FileField(blank=True, null=True, upload_to='', verbose_name=' نرم\u200cافزار اندروید')),
                ('web_app_address', models.URLField(blank=True, null=True, verbose_name='آدرس وب اپلیکیشن')),
                ('whatsapp_mz', models.URLField(blank=True, null=True, verbose_name='آدرس واتساپ MZ')),
                ('linkedin_mz', models.URLField(blank=True, null=True, verbose_name='لینکدین MZ')),
                ('instagram_mz', models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام MZ')),
                ('telegram_mz', models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام MZ')),
                ('vichat_mz', models.URLField(blank=True, null=True, verbose_name='ویچت MZ')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط ')),
            ],
            options={
                'verbose_name': 'اطلاعات صفحه ی اصلی',
                'verbose_name_plural': 'اطلاعات های صفحه ی اصلی',
            },
        ),
    ]
