# Generated by Django 5.0.1 on 2024-03-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinfo',
            name='carrier_owner_payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نرخ پرداختی صاحب حمل\u200cکننده'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='domestic_truck_payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نرخ پرداختی بار ماشینی داخلی'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='driver_payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نرخ پرداختی راننده'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='international_truck_payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نرخ پرداختی بار ماشینی خارجی'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='rail_cargo_payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نرخ پرداختی بار ریلی'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='wagon_owner_payment_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='نرخ پرداختی صاحب واگن'),
        ),
    ]
