# Generated by Django 5.0.1 on 2024-02-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepageinfo_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinfo',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='android_app',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=' نرم\u200cافزار اندروید'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='distance_covered',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کیلومتر مسیر طی شده'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='facebook_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس فیسبوک'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='instagram_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='loads_carried',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد بار حمل شده'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='phone_prefix',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='پیش\u200c شماره'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='ready_to_work_drivers',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد راننده\u200cهای آماده به کار'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='telegram_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='web_app_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس وب اپلیکیشن'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='whatsapp_address',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس واتساپ'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='working_days',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='روزهای کاری'),
        ),
    ]
