# Generated by Django 5.0.1 on 2024-03-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepageinfo_carrier_owner_payment_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageinfo',
            name='carrier_owner_payment_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی صاحب حمل\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='domestic_truck_payment_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی بار ماشینی داخلی'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='driver_payment_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی راننده'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='international_truck_payment_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی بار ماشینی خارجی'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='rail_cargo_payment_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی بار ریلی'),
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='wagon_owner_payment_rate',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی صاحب واگن'),
        ),
    ]
