# Generated by Django 5.0.1 on 2024-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepageinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinfo',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
    ]
