# Generated by Django 5.0.1 on 2024-02-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepageinfo_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageinfo',
            name='instagram_mz',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام MZ'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='linkedin_mz',
            field=models.URLField(blank=True, null=True, verbose_name='لینکدین MZ'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='telegram_mz',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام MZ'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='vichat_mz',
            field=models.URLField(blank=True, null=True, verbose_name='ویچت MZ'),
        ),
        migrations.AddField(
            model_name='homepageinfo',
            name='whatsapp_mz',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس واتساپ MZ'),
        ),
    ]
