# Generated by Django 5.0.1 on 2024-03-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepageinfo_carrier_owner_payment_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageinfo',
            name='international_truck_payment_rate',
        ),
        migrations.AlterField(
            model_name='homepageinfo',
            name='domestic_truck_payment_rate',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='نرخ پرداختی اعلام بار'),
        ),
    ]
