# Generated by Django 5.0.1 on 2024-03-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='reason',
            field=models.TextField(verbose_name='دلیل تراکنش'),
        ),
    ]
