# Generated by Django 5.0.1 on 2024-02-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagon_owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wagondetails',
            name='wagon_counts',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='تعداد واگن'),
        ),
    ]
