# Generated by Django 5.0.1 on 2024-02-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagon_owner', '0002_wagondetails_wagon_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wagondetails',
            name='wagon_counts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد واگن'),
        ),
    ]
