# Generated by Django 5.0.1 on 2024-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='account_type',
            field=models.CharField(choices=[('صاحب بار', 'صاحب بار'), ('صاحب حمل کننده', 'صاحب حمل کننده'), ('راننده', 'راننده')], max_length=150, verbose_name='نوع کاربری'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='importance_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='درجه اهمیت'),
        ),
    ]
