# Generated by Django 5.0.1 on 2024-02-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_tickets_account_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'درخواست پشتیبانی', 'verbose_name_plural': 'درخواست های پشتیبانی'},
        ),
    ]
